// Generated by CoffeeScript 1.3.3
(function() {
  var SaveCanvas;

  SaveCanvas = (function() {

    SaveCanvas.prototype.imageType = "jpeg";

    function SaveCanvas(url) {
      this.url = url;
      this.mime = "image/" + this.imageType;
    }

    SaveCanvas.prototype.hashList = [];

    SaveCanvas.prototype.save = function(canvas, formData) {
      var boundaryLine, boundaryStr, crlf, dataArray, img_data, k, kvChunk, v, xhr;
      img_data = canvas.toDataURL(this.mime).replace("data:" + this.mime + ";base64,", "");
      crlf = "\r\n";
      boundaryStr = "multipart_form_boundary_" + (new Date).getTime();
      boundaryLine = "--" + boundaryStr;
      kvChunk = function(k, v) {
        return boundaryLine + crlf + ("Content-Disposition: form-data; name=\"" + k + "\"") + crlf + crlf + v;
      };
      xhr = new XMLHttpRequest();
      xhr.open("POST", this.url, true);
      xhr.setRequestHeader("Content-Type", "multipart/form-data; boundary=" + boundaryStr);
      dataArray = [boundaryLine, 'Content-Disposition: form-data; name="canvas_upload"; ' + 'filename="frame.' + this.imageType + '"', "Content-Type: application/octet-stream", "", img_data];
      dataArray = dataArray.concat((function() {
        var _results;
        _results = [];
        for (k in formData) {
          v = formData[k];
          _results.push(kvChunk(k, v));
        }
        return _results;
      })());
      dataArray.push(boundaryLine);
      return xhr.send(dataArray.join(crlf));
    };

    return SaveCanvas;

  })();

  window.SaveCanvas = SaveCanvas;

}).call(this);
