// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TextLabel = (function(_super) {

    __extends(TextLabel, _super);

    function TextLabel(textBody) {
      this.closeButton = null;
      this.group = null;
      this.load_left = null;
      this.load_top = null;
      TextLabel.__super__.constructor.call(this, textBody, {
        textAlign: 'center',
        originX: 'center',
        originY: 'center',
        fontFamily: 'Averia Sans Libre'
      });
    }

    TextLabel.prototype.init = function() {
      var cb, imgElement;
      imgElement = document.createElement('img');
      imgElement.src = '/static/images/close-24.png';
      cb = new fabric.Image(imgElement, {
        originX: 'left',
        originY: 'top',
        left: this.getWidth() / 2 - 12,
        top: -this.getHeight() / 2,
        opacity: 0
      });
      this.closeButton = cb;
      canvas.bringToFront(cb);
      if (this.load_left === null) {
        this.load_left = 100;
      }
      if (this.load_top === null) {
        this.load_top = 100;
      }
      this.group = new TextGroup(this, [this, cb], {
        left: this.load_left,
        top: this.load_top
      });
      window.textList.push(this);
      return console.log('Total number of text elements ' + window.textList.length);
    };

    TextLabel.prototype.addToCanvas = function() {
      return canvas.add(this.group);
    };

    TextLabel.prototype.setLeft = function(pos) {
      return this.group.setLeft(pos);
    };

    TextLabel.prototype.setTop = function(pos) {
      return this.group.setTop(pos);
    };

    TextLabel.prototype.modified = function() {};

    TextLabel.prototype.selected = function() {
      this.closeButton.set('opacity', 1);
      return canvas.renderAll();
    };

    TextLabel.prototype.cleared = function() {
      this.closeButton.set('opacity', 0);
      return canvas.renderAll();
    };

    TextLabel.prototype.saveToJSON = function() {
      var jsonObj;
      jsonObj = {};
      jsonObj['text'] = this.getText();
      jsonObj['left'] = this.group.getLeft();
      jsonObj['top'] = this.group.getTop();
      console.log(jsonObj);
      return jsonObj;
    };

    TextLabel.prototype.restoreFromJSON = function(json) {
      this.load_left = json['left'];
      this.load_top = json['top'];
      this.setText(json['text']);
      this.setCoords();
      this.init();
      return this.addToCanvas();
    };

    return TextLabel;

  })(fabric.Text);

  window.TextGroup = (function(_super) {

    __extends(TextGroup, _super);

    function TextGroup(text, list, object) {
      this.text = text;
      TextGroup.__super__.constructor.call(this, list, object);
    }

    TextGroup.prototype.modified = function() {
      return this.text.modified();
    };

    TextGroup.prototype.selected = function() {
      return this.text.selected();
    };

    TextGroup.prototype.cleared = function() {
      return this.text.cleared();
    };

    TextGroup.prototype.setText = function(text) {
      return this.text.setText(text);
    };

    TextGroup.prototype.getText = function() {
      return this.text.getText();
    };

    TextGroup.prototype.shouldClose = function(point) {
      var cb, idx;
      cb = this.text.closeButton;
      if (cb.containsPoint(point)) {
        canvas.remove(this.text);
        canvas.remove(cb);
        canvas.remove(this);
        idx = window.textList.indexOf(this.text);
        if (idx >= 0) {
          return window.textList.splice(idx, 1);
        }
      }
    };

    TextGroup.prototype.saveToJSON = function() {
      var jsonObj;
      jsonObj = {};
      jsonObj['left'] = this.getLeft();
      return jsonObj['top'] = this.getTop();
    };

    TextGroup.prototype.restoreFromJSON = function(json) {
      this.setLeft(json['left']);
      this.setTop(json['top']);
      canvas.add(this);
      return this.setCoords();
    };

    return TextGroup;

  })(fabric.Group);

}).call(this);
