// Generated by CoffeeScript 1.6.1
(function() {

  window.Tracker = (function() {

    function Tracker() {}

    Tracker.prototype.parent = null;

    Tracker.prototype.element = null;

    Tracker.prototype.count = 0;

    Tracker.prototype.height = 30;

    Tracker.prototype.targetSprite = null;

    Tracker.prototype.history = [0];

    Tracker.prototype.latched = false;

    Tracker.prototype.createElement = function(sourceId, target) {
      var className, el;
      el = document.createElement('div');
      className = 'measure-follow';
      if (sourceId === 'iact_toggle') {
        className = className + ' iact';
      } else {
        className = className + ' counts';
      }
      el.className = className;
      el.innerHTML = 0;
      el["data-follows"] = target.spriteId;
      $(el).css({
        position: 'absolute',
        width: '40px',
        height: '' + this.height + 'px'
      });
      $(el).css('top', target.getTop() + target.getHeight() / 2 - this.height);
      $(el).css('left', target.getLeft() + target.getWidth() / 2);
      $('#construction_frame').append(el);
      this.element = el;
      return target.countElement = this;
    };

    Tracker.prototype.update = function() {
      var left, top;
      top = this.parent.getTop() + this.parent.getHeight() / 2 - this.height;
      left = this.parent.getLeft() + this.parent.getWidth() / 2;
      $(this.element).css({
        top: top,
        left: left
      });
      return $(this.element).html(this.count);
    };

    Tracker.prototype.remove = function() {
      $(this.element).remove();
      if (this.parent.measureObject === this) {
        return this.parent.measureObject = null;
      }
    };

    Tracker.prototype.interactCheck = function() {
      if (this.parent.trueIntersectsWithObject(this.targetSprite)) {
        if (!this.latched) {
          this.count += 1;
          this.latched = true;
        }
      } else {
        this.latched = false;
      }
      this.history.push(this.count);
      return this.update();
    };

    return Tracker;

  })();

}).call(this);
